modLoader="javafml"
loaderVersion="[39,)"
license="GNU 3.0"
issueTrackerURL="https://github.com/DancerVlt69/SlabsNstairs/issues"

[[mods]]
modId="slabsnstairs"
version="0.0.1.111"
displayName="SnS - Slabs 'n Stairs"
credits="Forge-Team (mdk-file), JetBrains (IntelliJ-IDEA), Kaupenjoe (YT-tuts), & much more"
displayURL="https://minecraftforge.net | https://jetbrains.com | https://tutorialsbykaupenjoe.net"
authors="DancerVlt69"
description='''
SnS - Slabs 'n Stairs - will add some simple blocks to your Minecraft Java Edition'''

[[dependencies.slabsnstairs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slabsnstairs]]
    modId="forge"
    mandatory=true
    versionRange="[39.,)"
    ordering="NONE"
    side="BOTH"


