modLoader="javafml"
loaderVersion="[41,)"
license="GNU 3.0"
issueTrackerURL="https://github.com/DancerVlt69/atm-SlabsNstairs/issues"

[[mods]]
modId="slabsnstairs"
version="${file.jarVersion}"
displayName="All the Missing - Slabs 'n Stairs"
credits='''Forge-Team (mdk-file), JetBrains (IntelliJ-IDEA), Kaupenjoe (YT-tuts), & much more
https://minecraftforge.net | https://jetbrains.com | https://tutorialsbykaupenjoe.net'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/slabs-n-stairs"
logoFile="logo.png"
authors="DancerVlt69"
description='''
All the Missing (ATM) - Slabs 'n Stairs - will add a lot of missing Slabs, Stairs, and more to your Minecraft Java Edition'''

[[dependencies.slabsnstairs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slabsnstairs]]
    modId="forge"
    mandatory=true
    versionRange="[41.,43.)"
    ordering="NONE"
    side="BOTH"


